lib/spree_contact_us/config/routes.rb
Spree::Core::Engine.routes.draw do
 
  resources :contact_us, only: [:new, :create]
  namespace :admin do
    resources :contact_us, only: [:index, :show, :destroy]
  end 	

end

lib/spree_contact_us/app/models/spree/contact_us.rb
module Spree
  class ContactUs < Spree::Base
  
  end
end  	

lib/spree_contact_us/app/controllers/spree/admin/contact_us_controller.rb
module Spree
  module Admin
    class ContactUsController < Spree::Admin::BaseController
      before_action :find_contact, except: [:index]

      def index
      	@contacts = Spree::ContactUs.all
      end 
      def show
      end 
      def destroy
        @contact.destroy
        redirect_to admin_contact_us_path
      end 	
      
      private
        
        def find_contact
          @contact = Spree::ContactUs.find(params[:id])
        end
    end
  end
end

lib/spree_contact_us/app/controllers/spree/contact_us_controller.rb
module Spree
  class ContactUsController < Spree::StoreController

    def new 
      @contact_us = ContactUs.new
    end

    def create
      @contact_us = ContactUs.new(contact_params)
      if @contact_us.save
        flash[:success] =  'Your topic has been sent, we will contact you'
        redirect_to root_path
      else
        render :new
      end
    end 

    private
      def contact_params
        params.require(:contact_us).permit(:topic, :email)
      end 
  end
end

lib/spree_contact_us/app/views/spree/admin/contact_us/index.html.erb
<fieldset>
  <legend><%= 'Topics' %></legend>
  <table class="table table-striped table-bordered">  
    <tr>
      <th><%= 'Email' %></th>
      <th><%= 'Topic' %></th>
      <th><%= 'Delete' %></th>
    </tr> 
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= contact.topic %></td>
        <td><%= link_to 'Delete', admin_contact_u_path(contact.id),:method => :delete, class: 'details'   %> </td>  
       </tr>
    <% end %>
  </table>
</fieldset>

lib/spree_contact_us/app/views/spree/contact_us/_form.html.erb
 <fieldset>
   <legend><%='Contact us' %></legend>
   
   <%= form_for @contact_us,url: contact_us_path , html: {class: 'form-horizontal', role: 'form', multipart: true} do |form| %>       
     <div class='form-group'>
       <div class='col-sm-10'>
         <%= form.text_field :topic, placeholder: 'Topic', class: 'form-control' %>
       </div>
     </div>

     <div class='form-group'>
       <div class='col-sm-10'>
         <%= form.text_field :email, placeholder: 'Email', class: 'form-control' %>
       </div>
     </div>         
     
     <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
         <%= form.submit "Submit" , class: 'btn btn-default' %>
       </div>
     </div>
             
  <% end %>
</fieldset>

lib/spree_contact_us/app/views/spree/contact_us/new.html.erb
<%= render 'form' %>